VERSION = 0.1.2
PASSWORD = "foxiot"
IMAGE_PREFIX = root_example_$(VERSION)
MODEL = wolf
INITRD_LIST = rootfs.list
ROOTFS_LIST = initrd.list
IMAGE_ITS ?= image.its
DRAM ?= NUC980DF71YC.ini
DEVICETREE_DIR_PATH=devicetrees

include ../../base/Makefile_dist.inc
